name: Continuous Deployment

on:
    push:
        branches:
            - main

jobs:
    installation:
        runs-on: self-hosted
        steps:
            - name: Checkout main branch
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'

            - name: Install Server Dependencies
              run: npm ci

            # Removed the permissions thing from here
            # Trying to figure out the CI/CD errors

            # - name: Test application
            #   run: npm test

            # - name: Install Client Dependencies
            #   # run: npm ci --legacy-peer-deps
            #   run: npm ci
            #   working-directory: ./client

    restart_server:
        needs: installation
        runs-on: self-hosted
        steps:
            - name: Set up environment
              env:
                  NODE_ENV: production
                  mongoURI: ${{ secrets.MONGOURI }}
                  jwtSecret: ${{ secrets.JWTSECRET }}
                  resetPasswordKey: ${{ secrets.RESETPASSWORDKEY }}
                  GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
                  calendlyID: ${{ secrets.CALENDLYID }}
                  calendlySecret: ${{ secrets.CALENDLYSECRET }}
                  cloud_name: ${{ secrets.CLOUD_NAME }}
                  cloudinary_api_key: ${{ secrets.CLOUDINARY_API_KEY }}
                  cloudinary_api_secret: ${{ secrets.CLOUDINARY_API_SECRET }}
                  mailChimpApiKey: ${{ secrets.MAILCHIMP_API_KEY }}
                  eventbritePrivateToken: ${{ secrets.EVENTBRITEPRIVATETOKEN }}
                  courierApiKey: ${{ secrets.COURIER_API_KEY }}
                  googleDriveApiKey: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
                  googleDriveRootFolder: ${{ secrets.GOOGLE_DRIVE_ROOT_FOLDER }}
                  SUPPRESS_NO_CONFIG_WARNING: TRUE
              run: |
                  # Verify the environment variables are set (optional)
                  echo "NODE_ENV=$NODE_ENV"
                  echo "mongoURI=$mongoURI"
                  echo "jwtSecret=$jwtSecret"

            - name: Restart server
              #environment variables set in GitHub Secrets (don't use quotes in values!)
              #"pm2 reload server --update-env" INSTEAD OF "pm2 restart server --update-env" to have zero downtime
              run: |
                  export SUPPRESS_NO_CONFIG_WARNING=TRUE
                  pm2 reload server --update-env
                  pm2 save
                  sudo service nginx restart

    # build_client:
    #     needs: installation
    #     runs-on: self-hosted
    #     defaults:
    #         run:
    #             working-directory: ./client
    #     steps:
    #         - name: Build Client
    #           run: npm run build
    #           env:
    #               CI: false
