name: Continuous Deployment

on:
    push:
        branches:
            - main

jobs:
    installation:
        runs-on: self-hosted
        steps:
            - name: Checkout main branch
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'

            - name: Install Server Dependencies
              run: npm ci

            # Removed the permissions thing from here
            # Trying to figure out the CI/CD errors

            # - name: Test application
            #   run: npm test

            # - name: Install Client Dependencies
            #   # run: npm ci --legacy-peer-deps
            #   run: npm ci
            #   working-directory: ./client

    restart_server:
        needs: installation
        runs-on: self-hosted
        steps:
            - name: Restart server
              #environment variables set in GitHub Secrets (don't use quotes in values!)
              #"pm2 reload server --update-env" INSTEAD OF "pm2 restart server --update-env" to have zero downtime
              run: |
                  unset mongoURI jwtSecret resetPasswordKey GOOGLE_MAPS_API_KEY calendlyID calendlySecret cloud_name cloudinary_api_key cloudinary_api_secret mailChimpApiKey eventbritePrivateToken courierApiKey googleDriveApiPrivateKeyPath
                  export NODE_ENV='production'
                  echo "${{ secrets.GOOGLE_DRIVE_API_PRIVATE_KEY }}" > gd_private_key.pem
                  chmod 600 gd_private_key.pem
                  export googleDriveApiPrivateKeyPath=$(pwd)/gd_private_key.pem
                  export mongoURI=${{secrets.MONGOURI}}
                  export jwtSecret=${{secrets.JWTSECRET}}
                  export resetPasswordKey=${{secrets.RESETPASSWORDKEY}}
                  export GOOGLE_MAPS_API_KEY=${{secrets.GOOGLE_MAPS_API_KEY}}
                  export calendlyID=${{secrets.CALENDLYID}}
                  export calendlySecret=${{secrets.CALENDLYSECRET}}
                  export cloud_name=${{secrets.CLOUD_NAME}}
                  export cloudinary_api_key=${{secrets.CLOUDINARY_API_KEY}}
                  export cloudinary_api_secret=${{secrets.CLOUDINARY_API_SECRET}}
                  export mailChimpApiKey=${{secrets.MAILCHIMP_API_KEY}}
                  export eventbritePrivateToken=${{secrets.EVENTBRITEPRIVATETOKEN}}
                  export courierApiKey=${{secrets.COURIER_API_KEY}}
                  export SUPPRESS_NO_CONFIG_WARNING=TRUE
                  pm2 reload server --update-env
                  pm2 save
                  sudo service nginx restart

    # build_client:
    #     needs: installation
    #     runs-on: self-hosted
    #     defaults:
    #         run:
    #             working-directory: ./client
    #     steps:
    #         - name: Build Client
    #           run: npm run build
    #           env:
    #               CI: false
