name: Continuous Deployment

on:
    push:
        branches:
            - main

jobs:
    installation:
        runs-on: self-hosted
        steps:
            - name: Checkout main branch
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'

            - name: Install Server Dependencies
              run: |
                  sudo rm -rf uploads
                  npm ci

            # Removed the permissions thing from here
            # Trying to figure out the CI/CD errors

            # - name: Test application
            #   run: npm test

            # - name: Install Client Dependencies
            #   # run: npm ci --legacy-peer-deps
            #   run: npm ci
            #   working-directory: ./client

    restart_server:
        needs: installation
        runs-on: self-hosted
        steps:
            - name: Setup Environment Variables and Restart server
              #environment variables set in GitHub Secrets (don't use quotes in values!)
              #"pm2 reload server --update-env" INSTEAD OF "pm2 restart server --update-env" to have zero downtime
              #I moved googleDriveApiClientEmail, googleDriveApiPrivateKeyPath, and googleDriveRootFolder to '../../../porchlight-config/default.json' on the server, because I had too much trouble with the GitHub Secrets and I guess the length of the Google Drive Private Key
              run: |
                  export SUPPRESS_NO_CONFIG_WARNING=TRUE
                  pm2 reload server --update-env
                  pm2 save
                  sudo service nginx restart

    # build_client:
    #     needs: installation
    #     runs-on: self-hosted
    #     defaults:
    #         run:
    #             working-directory: ./client
    #     steps:
    #         - name: Build Client
    #           run: npm run build
    #           env:
    #               CI: false
