name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci

      # - name: Test application
      #   run: npm test

      - name: Build application
        run: |
          cd client
          npm ci
          npm run build
          pm2 stop server
          pm2 start server
          pm2 save
          sudo service nginx restart
